server:
  port: ${PORT:8080}

spring:
  profiles:
    active: railway
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# UPI Configuration (for payment service)
upi:
  merchant:
    id: ${UPI_MERCHANT_ID:merchant@upi}
    name: ${UPI_MERCHANT_NAME:Payment Gateway}

# Bank API Configuration (for payment service)
bank:
  api:
    url: ${BANK_API_URL:https://api.bank.com}
    key: ${BANK_API_KEY:bank_api_key}

# Logging configuration
logging:
  level:
    com.paymentgateway: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized