version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis

  # Auth Service
  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis

  # Merchant Service
  merchant-service:
    build: ./backend/merchant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres

  # Payment Service
  payment-service:
    build: ./backend/payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis

  # Transaction Service
  transaction-service:
    build: ./backend/transaction-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api-gateway

  # Test Merchant App
  test-merchant:
    build: ./test-merchant-app
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_PAYMENT_GATEWAY_URL=http://localhost:8080
      - REACT_APP_MERCHANT_API_KEY=test_api_key_123
      - PORT=3001
    depends_on:
      - api-gateway

volumes:
  postgres_data: