server:
  port: 8083

spring:
  application:
    name: payment-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_gateway
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  redis:
    host: localhost
    port: 6379

jwt:
  secret: mySecretKeyForPaymentGatewayApplication
  expiration: 86400000

# UPI Configuration
upi:
  merchant:
    id: "merchant@upi"
    name: "Payment Gateway"
  
# Bank API Configuration (placeholder)
bank:
  api:
    url: "https://api.bank.com"
    key: "bank_api_key"

logging:
  level:
    com.paymentgateway: DEBUG