server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/payments/**
        
        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/transactions/**
        
        - id: merchant-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/merchants/**
        
        - id: admin-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**
        
        - id: test-merchant-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/test-merchant/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG